apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: busyboxapps.busybox.operator.com
spec:
  group: busybox.operator.com
  names:
    kind: BusyBoxApp
    listKind: BusyBoxAppList
    plural: busyboxapps
    singular: busyboxapp
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
